# Generated by Django 3.1.7 on 2021-04-14 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Введите название возрастной категории (например, дети).', max_length=50)),
                ('ageto', models.IntegerField(help_text='Введите верхнюю границу возрастной категории в годах (например, 14).', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Введите город/иной населённый пункт (с большой буквы).', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='Введите фамилию, имя и отчество тренера (с большой буквы, полностью).', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('datestart', models.DateField(auto_now=True)),
                ('dateend', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Fencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('rate', models.IntegerField()),
                ('coach', models.ManyToManyField(help_text='Выберите тренера', to='catalog.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Введите уровень соревнований (например, первенство города).', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sportclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportclub', models.CharField(help_text='Введите название спортклуба (например, Виктория).', max_length=300)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.city')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.competition')),
                ('fencer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.fencer')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Введите название места (например, Спортзал №2 НГУ).', max_length=300)),
                ('adres', models.CharField(help_text='Введите адрес (улица, дом, корпус при необходимости).', max_length=200)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.city')),
            ],
        ),
        migrations.AddField(
            model_name='fencer',
            name='sportclub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.sportclub'),
        ),
        migrations.AddField(
            model_name='competition',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.level'),
        ),
        migrations.AddField(
            model_name='competition',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.place'),
        ),
    ]
