# Generated by Django 3.1.7 on 2021-05-30 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(help_text='Введите гендерную принадлежность спортсмена.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(help_text='Введите разряд/звание спортсмена (например, 1юн или МСМК)', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(help_text='Введите вид оружия (например, шпага или рапира)', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='ageto',
            field=models.IntegerField(help_text='Введите верхнюю границу возрастной категории в годах (например, 14).'),
        ),
        migrations.RemoveField(
            model_name='fencer',
            name='coach',
        ),
        migrations.AddField(
            model_name='fencer',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.coach'),
        ),
        migrations.AddField(
            model_name='competition',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.gender'),
        ),
        migrations.AddField(
            model_name='competition',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.weapon'),
        ),
        migrations.AddField(
            model_name='fencer',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.gender'),
        ),
        migrations.AddField(
            model_name='fencer',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.rank'),
        ),
    ]
