# Generated by Django 3.1.7 on 2021-05-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210530_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['result']},
        ),
        migrations.AlterField(
            model_name='competition',
            name='dateend',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='datestart',
            field=models.DateField(),
        ),
    ]
